version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SEED=the_super_secret_seed_*!123
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=465
      - EMAIL_USER=user@mail.com
      - EMAIL_PASSWORD=xoxo xoxo xoxo xoxo
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:16.5
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres-data:
